import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newRoom,changeRoom,tickRoom,standings,winners,publicRoom,type Room} from '../lib/series.ts';
import {createWorld,step,acceptActions} from '../lib/game.ts';
function room(n=2){const r=newRoom({id:'p0',name:'A',hash:'secret',seq:-1,seen:0,ready:false},0);for(let i=1;i<n;i++)r.seats.push({id:`p${i}`,name:String(i),hash:`secret${i}`,seq:-1,seen:0,ready:false});return r;}
function ready(r:Room,now:number){for(const s of r.seats)changeRoom(r,s,{op:'ready',match:r.match,round:r.round,ready:true},now);tickRoom(r,now+3000);assert.equal(r.status,'running');}
function finish(r:Room,scores:number[],now:number){r.world!.players.forEach((p,i)=>{p.score=scores[i];p.collected=scores[i]+5;p.deaths=i;});r.world!.status='finished';tickRoom(r,now);}
test('preparation never forces start; readiness can cancel countdown',()=>{const r=room();changeRoom(r,r.seats[0],{op:'timer',match:1,round:1,seconds:600},0);tickRoom(r,900000);assert.equal(r.status,'waiting');for(const s of r.seats)changeRoom(r,s,{op:'ready',match:1,round:1,ready:true},900000);assert.equal(r.status,'countdown');changeRoom(r,r.seats[1],{op:'ready',match:1,round:1,ready:false},901000);tickRoom(r,904000);assert.equal(r.status,'waiting');});
test('two wins end BO3 early and settlement is idempotent',()=>{const r=room();ready(r,0);finish(r,[20,10],4000);assert.equal(r.status,'intermission');assert.equal(r.round,2);tickRoom(r,5000);assert.equal(r.history.length,1);ready(r,6000);assert.equal(r.world!.players[0].base.x,865);finish(r,[30,10],10000);assert.equal(r.status,'finished');assert.deepEqual(winners(r),['p0']);assert.equal(r.history.length,2);});
test('draws count toward three rounds, but do not award wins',()=>{const r=room();for(let i=0;i<3;i++){ready(r,i*10000);finish(r,[10,10],i*10000+4000);}assert.equal(r.status,'finished');assert.deepEqual(standings(r).map(p=>p.wins),[0,0]);assert.deepEqual(winners(r),['p0','p1']);});
test('multiplayer averages tied rank points and rotates spawns',()=>{const r=room(4);const bases=[];for(let i=0;i<3;i++){ready(r,i*10000);bases.push(r.world!.players[0].base);finish(r,[30,30,10,0],i*10000+4000);}assert.equal(r.status,'finished');assert.deepEqual(r.history[0].players.map(p=>p.points),[3.5,3.5,2,1]);assert.equal(new Set(bases.map(p=>JSON.stringify(p))).size,3);assert.deepEqual(winners(r),['p0','p1']);assert.equal(standings(r)[0].points,10.5);});
test('three player totals resolve by delivered energy then shared winner',()=>{const r=room(3);const scores=[[100,10,0],[10,40,0],[20,20,0]];for(let i=0;i<3;i++){ready(r,i*10000);finish(r,scores[i],i*10000+4000);}assert.equal(standings(r)[0].points,standings(r)[1].points);assert.deepEqual(winners(r),['p0']);});
test('late round and match packets cannot act or ready next round',()=>{const r=room();ready(r,0);finish(r,[20,10],4000);assert.throws(()=>changeRoom(r,r.seats[0],{op:'ready',match:1,round:1,ready:true},5000));ready(r,6000);changeRoom(r,r.seats[0],{op:'sync',match:1,round:1,seq:99,actions:{'p0-0':{type:'move',x:500,y:400}}},9100);assert.equal(r.world!.robots[0].action.type,'idle');finish(r,[20,10],10000);assert.throws(()=>changeRoom(r,r.seats[1],{op:'rematch',match:1,round:2},11000));changeRoom(r,r.seats[0],{op:'rematch',match:1,round:2},11000);assert.equal(r.match,2);assert.equal(r.history.length,0);assert.equal(r.seats[0].hash,'secret');assert.throws(()=>changeRoom(r,r.seats[0],{op:'ready',match:1,round:1,ready:true},12000));assert(!JSON.stringify(publicRoom('ABCDEF',r,1,12000)).includes('secret'));});
test('duplicate sequence and disconnected readiness are rejected',()=>{const r=room();ready(r,0);changeRoom(r,r.seats[0],{op:'sync',match:1,round:1,seq:2,actions:{'p0-0':{type:'move',x:500,y:400}}},4000);changeRoom(r,r.seats[0],{op:'sync',match:1,round:1,seq:1,actions:{'p0-0':{type:'idle'}}},4001);assert.equal(r.world!.robots[0].action.type,'move');finish(r,[20,10],5000);changeRoom(r,r.seats[0],{op:'ready',match:1,round:2,ready:true},6000);tickRoom(r,22000);assert.equal(r.seats[0].ready,false);});
test('core uses one slot, statistics count delivery and destruction',()=>{const w=createWorld(),r=w.robots[0],t=w.resources.find(t=>t.core)!;r.x=t.x;r.y=t.y;acceptActions(w,'p0',{[r.id]:{type:'gather',target_id:t.id}});step(w,.05);assert.equal(r.cargo,20);assert.equal(r.cargoSlots,1);assert.equal(w.players[0].collected,20);r.action={type:'idle'};r.x=w.players[0].base.x;r.y=w.players[0].base.y;step(w,.05);assert.equal(w.players[0].score,20);assert.equal(r.cargoSlots,0);r.x=450;r.hp=0;step(w,.05);assert.equal(w.players[0].deaths,1);step(w,.05);assert.equal(w.players[0].deaths,1);});
