import type {RoomView} from '@/lib/room-view';
const clock=(ms:number)=>{const s=Math.max(0,Math.ceil(ms/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;};
export default function SeriesPanel({room,playerId,busy,onReady,onAction}:{room:RoomView;playerId:string;busy:boolean;onReady:()=>void;onAction:(op:string,extra?:object)=>void}){
  const prep=room.status==='waiting'||room.status==='intermission',self=room.players.find(p=>p.id===playerId),last=room.history.at(-1);
  return <section className="series-panel panel" aria-label="赛程与复盘">
    <div className="series-heading"><div><div className="eyebrow">{room.players.length===2?'BEST OF THREE':'THREE ROUND SERIES'}</div><h2>{room.players.length===2?'三局两胜':'三轮积分赛'} <span>第 {room.round} / 3 轮</span></h2></div><div className="round-dots">{[1,2,3].map(n=><span key={n} className={room.history.some(h=>h.round===n)?'done':n===room.round?'current':''}>{n}</span>)}</div></div>
    <div className="ready-players">{room.players.map((p,i)=><span key={p.id} style={{borderColor:['#54e5bb','#ff7e83','#f2c66f','#aa9cff'][i]}}>{p.name}{p.id===playerId?'（你）':''} · {room.status==='running'?'对战中':p.ready?'已准备':'调整策略'}</span>)}</div>
    {(prep||room.status==='countdown')&&<div className="series-actions"><p>{room.status==='countdown'?`${clock(room.starts-room.serverNow)} 后开战`:room.prepEnds?room.prepEnds>room.serverNow?`调整提醒 ${clock(room.prepEnds-room.serverNow)} · 全员准备才开战`:'提醒时间已到，可继续修改；不会强制开战':'准备不限时 · 验证代码后准备'}<small>代码保留，下一轮清空 memory 并轮换出生位置。</small></p><button className="primary small" disabled={busy} onClick={onReady}>{self?.ready?'取消准备':'验证并准备'}</button>{prep&&playerId==='p0'&&<><button className="plain-button" onClick={()=>onAction('timer',{seconds:room.prepEnds?120:600})}>{room.prepEnds?'延长 2 分钟':'10 分钟提醒'}</button>{!!room.prepEnds&&<button className="plain-button" onClick={()=>onAction('timer',{seconds:0})}>不限时</button>}</>}</div>}
    {room.status==='finished'&&<div className="series-actions"><p className="champion">{room.winners.length>1?'并列优胜 / 平局：':'整场冠军：'}{room.players.filter(p=>room.winners.includes(p.id)).map(p=>p.name).join('、')}<small>三轮内完成结算，草稿可继续用于下一场。</small></p>{playerId==='p0'?<button className="primary small" disabled={busy} onClick={()=>onAction('rematch')}>原房间再赛</button>:<span>等待房主再开一场</span>}</div>}
    {last&&<details className="round-review" open={room.status==='intermission'||room.status==='finished'}><summary>第 {last.round} 轮复盘 · 已完成 {room.history.length} 轮</summary><div className="stats-scroll"><table><thead><tr><th>玩家</th><th>采集 EP</th><th>交付 EP</th><th>死亡</th><th>{room.players.length===2?'累计胜场':'本轮 / 总积分'}</th></tr></thead><tbody>{last.players.map(p=>{const total=room.standings.find(s=>s.id===p.id)!;return <tr key={p.id}><td>{total.name}</td><td>{p.collected}</td><td>{p.delivered}</td><td>{p.deaths}</td><td>{room.players.length===2?`${total.wins} 胜`:`${p.points} / ${total.points}`}</td></tr>;})}</tbody></table></div><div className="round-history">{room.history.map(h=><span key={h.round}>R{h.round} · {h.players.map(p=>`${room.players.find(s=>s.id===p.id)?.name} ${p.delivered}`).join(' / ')}</span>)}</div><p className="muted">采集多、交付少：检查返航与运输损失。死亡多：调整撤退阈值和交战距离。{room.players.length>2?'同名次平分所占名次积分；总分相同再比累计交付。':'单轮平局不计胜场；三局后胜场相同则整场平局。'}</p></details>}
  </section>;
}
